### ISSUE TITLE
Do not set keep alive interval on mOpts

### ISSUE THREAD

**Issue by flexiti** [ratmole/mqttClient#1]
> // Do not set keep alive interval on mOpts we keep track of it with alarm's

Can I have a question? :)
- Why You use "alarms" instead keep alive and Last Will ?
  Can I know why you decide on this?
- Keepalive is sent to a broker with connect message , so from that mement broker knows how long wait for message (or PING)  from the client.
  If client no sent messages, broker sends LWT.
  You're suggesting "Do not set keep alive interval"

**Comment by ratmole** [comment]
the code is based on the code of Jesse Farebrother: 
https://github.com/JesseFarebro/Android-Mqtt/blob/master/src/com/jessefarebro/mqtt/MqttService.java
and i decided to go with his implementation.
if you think that it needs to be changed go for it and let me know :)
